### ISSUE TITLE
[REQUEST] Add UnSub Module

### ISSUE THREAD

**Issue by aarhus** [avenjamin/awesome-freescout#1]
Please add this awesome module to the list:

The Module name:  UnSub

The repo URL:  https://github.com/aarhus/UnSub

A short description of the module: 

Adds the ability to for one click unsubscribe to mailing lists that support it

Thanks!

**Comment by avenjamin** [comment]
@aarhus nice module - you might want to look at adding an icon/image that appears on the modules page.
There's an `img` property you can add to the `modules.json` file. e.g:

"img": "/modules/my-awesome-module/img/module-image-256x256.png"

You might have to play around with the path a bit though. I stick my images in the `Public/img/` folder and reference them as above.

**Comment by aarhus** [comment]
Thanks for the heads up :-)
